Update UniversalCleanup

diff --git a/UniversalCleanup b/UniversalCleanup
--- a/UniversalCleanup
+++ b/UniversalCleanup
@@ -37,12 +37,21 @@ clean_directory() {
 
 yum_operations() {
 if ! command -v yum &> /dev/null; then
-  echo "Neither yum is Installed!"
+    echo "Neither yum is Installed!"
 else
-  yum update
-  yum upgrade
-  yum update --security
-  rm -rf /var/cache/yum/*
+    read -p "Are you sure you want to clear the yum cache? (y/n): " confirm
+
+    if [[ $confirm =~ ^[Yy]$ ]]; then
+        echo "Clearing yum cache..."
+        sudo rm -rf /var/cache/yum/*
+    else
+        echo "Skipping yum cache cleanup."
+    fi
+
+    sudo snap list --all | awk '/disabled/ { print $1, $3 }' | while read snap revision; do
+         sudo snap remove "$snap" --revision="$revision"
+    done
+    rm -rf /var/cache/yum/*
 fi
 }
 
@@ -52,71 +61,86 @@ if ! command -v nix &> /dev/null; then
 else
   nix-env -iA nixpkgs.nix
   nix-env -u '*'
-  nix-channel --update
   nix-collect-garbage -d
-  nix-collect-garbage --delete-old
   nix-store --gc
   nix-env --delete-generations old
 fi
 }
 
+dnf_operations() {
+    if ! command -v dnf &> /dev/null; then
+        echo "dnf is not installed!"
+    else
+        log_message "Starting DNF operations"
+        echo 'Cleaning local repository of packages...'
+        dnf autoremove -y
+        dnf clean all -y
+    fi
+}
+
+flatpak_operations() {
+    if ! command -v dnf &> /dev/null; then
+        echo "dnf is not installed!"
+    else
+        log_message "Starting DNF operations"
+        echo 'Cleaning local repository of packages...'
+        flatpak uninstall --unused
+        dnf clean all -y
+    fi
+}
 
 apt_operations() {
-if ! command -v apt &> /dev/null && ! command -v apt-get &> /dev/null; then
-  echo "Neither apt nor apt-get is installed!"
-else
-  log_message "Starting APT operations"
-  echo 'Updating package lists...'
-  apt-get update -y
-  echo 'Upgrading packages...'
-  apt-get upgrade -y
-  apt-get full-upgrade -y
-  echo 'Removing unused packages...'
-  apt-get autoremove --purge -y
-  echo 'Cleaning local repository of packages...'
-  apt autoclean
-  apt clean
-  apt -s clean
-  apt clean all
-  apt-get clean
-  apt-get autoclean
-fi
+    if ! command -v apt &> /dev/null && ! command -v apt-get &> /dev/null; then
+        echo "Neither apt nor apt-get is installed!"
+    else
+        log_message "Starting APT operations"
+        echo 'Cleaning local repository of packages...'
+
+        # Clean package cache using both apt and apt-get
+        apt clean -y
+        apt-get clean -y
+
+        # Optional: You can run autoclean, but it's typically not necessary after clean
+        apt autoclean -y
+        apt-get autoclean -y
+    fi
 }
 
 remove_old_kernels() {
 if ! command -v apt &> /dev/null && ! command -v apt-get &> /dev/null; then
-  echo "Neither apt is installed!"
+    echo "Neither apt is installed!"
 else
-  echo 'Removing old kernels...'
-  apt autoremove --purge -y
-  apt-get autoremove --purge -y
+    echo 'Removing old kernels...'
+    apt autoremove --purge -y
+    apt-get autoremove --purge -y
 fi
 
 }
 
 remove_old_configs() {
   for cmd in dpkg grep awk xargs; do
-    if ! command -v "$cmd" &> /dev/null; then
-      echo "$cmd is Missing!"
-    else
-      echo 'Removing old configuration files...'
-      dpkg -l | grep '^rc' | awk '{print $2}' | xargs -r dpkg --purge
-    fi
+      if ! command -v "$cmd" &> /dev/null; then
+          echo "$cmd Is Missing"
+      else
+          echo 'Removing old configuration files...'
+          dpkg -l | grep '^rc' | awk '{print $2}' | xargs -r dpkg --purge
+          sudo dpkg --purge $(dpkg --list | grep '^rc' | awk '{print $2}')
+      fi
   done
 }
 
 clean_docker() {
   if ! command -v "docker" &> /dev/null; then
-    echo "docker is Missing!"
+      echo "docker Is Missing"
   else
-    echo 'Cleaning Docker...'
-    docker system prune -a -f --volumes
+      echo 'Cleaning Docker...'
+      docker system prune -a -f --volumes
   fi
 }
 
 clean_journal() {
   if ! command -v "journalctl" &> /dev/null; then
-    echo "journalctl is Missing!"
+      echo "journalctl Is Missing"
   else
     echo 'Cleaning journal logs...'
     journalctl --vacuum-size=50M
@@ -125,7 +149,7 @@ clean_journal() {
 
 clean_systemd_resolved() {
   if ! command -v "systemctl" &> /dev/null; then
-    echo "systemctl is Missing!"
+      echo "systemctl Is Missing"
   else
     echo 'Cleaning systemd-resolved cache...'
     rm -rf /var/cache/systemd/resolved
@@ -135,7 +159,7 @@ clean_systemd_resolved() {
 
 clean_snaps() {
   if ! command -v "snap" &> /dev/null; then
-    echo "snap is Missing!"
+      echo "snap Is Missing"
   else
     echo 'Remove old snaps...'
     set -eu
@@ -146,9 +170,80 @@ clean_snaps() {
   fi
 }
 
+universal_update() {
+    echo "Starting system update process..."
+
+    # Update for APT-based systems
+    if command -v apt &> /dev/null; then
+        echo "APT package manager detected."
+        sudo apt update -y && sudo apt full-upgrade -y
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31mE: APT update/upgrade failed.\e[0m" >&2
+            exit 1
+        fi
+
+    # Update for DNF-based systems
+    elif command -v dnf &> /dev/null; then
+        echo "DNF package manager detected."
+        sudo dnf update -y
+        sudo dnf upgrade -y
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31mE: DNF update failed.\e[0m" >&2
+            exit 1
+        fi
+
+    # Update for YUM-based systems
+    elif command -v yum &> /dev/null; then
+        echo "YUM package manager detected."
+        sudo yum update -y
+        sudo yum update --security -y
+        sudo yum upgrade -y
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31mE: YUM update failed.\e[0m" >&2
+            exit 1
+        fi
+
+    # Update for Snap-based systems
+    elif command -v snap &> /dev/null; then
+        echo "Snap package manager detected."
+        sudo snap refresh
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31mE: Snap update failed.\e[0m" >&2
+            exit 1
+        fi
+
+    # Update for Nix-based systems
+    elif command -v nix-channel &> /dev/null; then
+        echo "Nix package manager detected."
+        sudo nix-channel --update
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31mE: Nix update failed.\e[0m" >&2
+            exit 1
+        fi
+
+    # Update for Flatpak-based systems
+    elif command -v flatpak &> /dev/null; then
+        echo "Flatpak package manager detected."
+        sudo flatpak update -y
+        if [ $? -ne 0 ]; then
+            echo -e "\e[31mE: Flatpak update failed.\e[0m" >&2
+            exit 1
+        fi
+
+    else
+        echo -e "\e[31mE: No Supported Package Manager Found.\e[0m" >&2
+        exit 1
+    fi
+
+    echo "System update completed successfully."
+}
+
+
 
 update_system() {
+  universal_update
   apt_operations
+  dnf_operations
   yum_operations
   nix_operations
   remove_old_kernels
